chore: Unit testing for adding target publish outputs
Reference: https://linear.app/speakeasy/issue/GEN-1670/firehydrant-mcp-not-publishing
Reference: https://github.com/speakeasy-api/sdk-gen-config/pull/85

Currently failing as sdk-gen-config requires update to support `mcp-typescript` target for NPM publishing:

```
--- FAIL: TestAddTargetPublishOutputs (0.00s)
    --- FAIL: TestAddTargetPublishOutputs/mcp-typescript-publishing (0.00s)
        /Users/bflad/src/github.com/speakeasy-api/sdk-generation-action/internal/run/run_test.go:222: expected map[publish_mcp_typescript:true], got map[publish_mcp_typescript:false]
```