fix: Ensure mcp-typescript target correctly sets publish_mcp_typescript output if NPM is configured (#231)
Reference: https://linear.app/speakeasy/issue/GEN-1670/firehydrant-mcp-not-publishing
Reference: https://github.com/speakeasy-api/sdk-gen-config/pull/85

Previously failing as sdk-gen-config required update to support `mcp-typescript` target for NPM publishing:

```
--- FAIL: TestAddTargetPublishOutputs (0.00s)
    --- FAIL: TestAddTargetPublishOutputs/mcp-typescript-publishing (0.00s)
        /Users/bflad/src/github.com/speakeasy-api/sdk-generation-action/internal/run/run_test.go:222: expected map[publish_mcp_typescript:true], got map[publish_mcp_typescript:false]
```

Updated github.com/speakeasy-api/sdk-gen-config@v1.31.2 with fix.