feat: Enable mcp-typescript handling and upgrade Alpine to 3.21 (#222)
Reference: https://linear.app/speakeasy/issue/GEN-1422/feature-initial-mcp-typescript-handling-in-sdk-generation-action

This change adds MCP TypeScript workflow and publishing handling to the GitHub Actions logic, similar to the existing TypeScript workflow and publishing handling. The directory/regenerated/publish outputs are duplicated for cases where the workflow contains multiple languages and where it'd be errant to, for example, release the TypeScript SDK, if there were only changes to the MCP TypeScript server.

The Alpine Linux upgrade (or alternatively using actions/setup-node) is required for NodeJS 22 support, otherwise on current image:

```
  WARN    can't compile - Dependency Version Mismatch - Install Node.js by following the instructions at https://nodejs.org/en/download/.
  Error: dependency version not met -- node - version 20.15.1 is less than required version 22.0.0
```

Verified with updated Docker image: https://github.com/bflad/petstore-mcp-typescript/pull/1